/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import ClassDoiTuong.TaiKhoan;
import ClassDoiTuong.BaoCao;
import ChucNang.Client; /*import vào Class Client có chứa các thuộc tính lưu dữ liệu bao gồm danh sách taiKhoan, danh sách thietBi, danh sách baoCao*/
import ClassDoiTuong.ThietBi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class GiaoDienKyThuatVien extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    DefaultTableModel model;

    public GiaoDienKyThuatVien() {
        initComponents();
        showktv();
    }

    /*Hiển thị danh sách vào bản trạng thái lỗi được giao*/
    public final void showktv() {
//        String[] columnNames={"Nhân Viên Báo","Mã Thiết Bị","Tên","Vị Trí","Loại Lỗi","Mô Tả","Ngày Báo Cáo","Tình Trạng"};
        model = (DefaultTableModel) ktv.getModel();
        model.setColumnIdentifiers(new Object[]{
            "ID", "Nhân Viên Báo", "Mã Thiết Bị", "Tên", "Vị Trí", "Loại Lỗi", "Mô Tả", "Ngày Báo Cáo", "Tình Trạng"
        });
        
        for (BaoCao baoCao : Client.danhSachBaoCao) {
            TaiKhoan t = new TaiKhoan();
            for (TaiKhoan taiKhoan : Client.danhSachTaiKhoan) { /*danhSachTaiKhoan Lấy trực tiếp từ Client*/
                if (taiKhoan.getId() == baoCao.getIdNguoiBaoCao()) {
                    t = taiKhoan;
                }
            }
            
            ThietBi tb = new ThietBi();
            for (ThietBi thietBi : Client.danhSachThietBi) {/*danhSachThietBi Lấy trực tiếp từ Client*/
                if (baoCao.getIdThietBiGapSuCo() == thietBi.getId()) {
                    tb = thietBi;
                }
            }
            
            model.addRow(new Object[]{
                baoCao.getId(), t.getTenNguoiDung(), baoCao.getIdThietBiGapSuCo(), tb.getTen(), tb.getViTri(), baoCao.getLoaiSuCo(), baoCao.getMoTaSuCo(), baoCao.getThoiGian(), tb.getTrangThai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ktv = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        upData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ktv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ktv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ktv.setEditingColumn(25);
        ktv.setRowHeight(25);
        jScrollPane3.setViewportView(ktv);

        jLabel1.setText("BẢN TRẠNG THÁI LỖI ĐƯỢC GIAO");

        upData.setText("Cập Nhật");
        upData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(upData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(upData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Kỹ Thuật Viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cap nhat bao cao
     * 
     * @param evt 
     */
    private void upDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDataActionPerformed
        /* Lay du lieu tu form */
        int idThietBi = (int) ktv.getValueAt(ktv.getSelectedRow(), 2);
        String trangThai = ktv.getValueAt(ktv.getSelectedRow(), 8).toString();
        
        /* Mo ket noi */
        Client client = new Client();
        
        /* Gui yeu cap nhat thiet bi */
        for (ThietBi tb : Client.danhSachThietBi) {
            if (tb.getId() == idThietBi) {
                tb.setTrangThai(trangThai);
                Client.thietBi = new ThietBi(tb);
            }
        }
        
        client.guiYeuCau("TB04");
        
        client.guiYeuCauHienThi("TB01");
        
        /* Cap nhat lai bang bao cao */
        showktv();
    }//GEN-LAST:event_upDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKyThuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienKyThuatVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable ktv;
    private javax.swing.JButton upData;
    // End of variables declaration//GEN-END:variables
}
